### ISSUE TITLE
Release v6.4.6

### ISSUE THREAD

**Issue by nayemDevs** [rtCamp/wp-menu-custom-fields#108]
- [ ] Prepare changelog and get it reviewed on Slack 
- [ ] Get confirmation from QA 
- [ ] Relese on WordPress.org

**Comment by prasadnevase** [comment]
@vk17-starlord - what is the status on this? 

I still see `Tested upto` to be 6.4.5 here - https://wordpress.org/plugins/wp-menu-custom-fields/

Next week WordPress 6.7 will be out.

**Comment by pavanpatil1** [comment]
Updated the tested upto version on wp.org - https://wordpress.org/plugins/wp-menu-custom-fields/#description

**Comment by nayemDevs** [comment]
Thanks, closing this issue.
