### ISSUE TITLE
Fatal error: Uncaught Error: Class 'WP_Menu_Custom_Fields\Inc\Plugin' not found 

### ISSUE THREAD

**Issue by rahul286** [rtCamp/wp-menu-custom-fields#28]
_Issue reported via [email](https://mail.google.com/mail/u/1/#inbox/FMfcgxwHMsSttPgmFzklSvHfhwMmMGbV)_
________

Hi 👋🏼 I've discover a bug with your wordpress plugin "WP Menu Custom Fields"

The error :
Fatal error: Uncaught Error: Class 'WP_Menu_Custom_Fields\Inc\Plugin' not found in C:\Users\user\local-sites-beta\inoxpluschr\app\public\wp-content\plugins\wp-menu-custom-fields\wp-menu-custom-fields.php on line 29
( ! ) Error: Class 'WP_Menu_Custom_Fields\Inc\Plugin' not found in C:\Users\user\local-sites-beta\inoxpluschr\app\public\wp-content\plugins\wp-menu-custom-fields\wp-menu-custom-fields.php on line 29
Call Stack
# Time Memory Function Location
1 0.0001 398632 {main}( ) ...\plugins.php:0
2 0.8459 18996072 plugin_sandbox_scrape( ) ...\plugins.php:177
3 0.8460 18996288 include( 'C:\Users\user\local-sites-beta\inoxpluschr\app\public\wp-content\plugins\wp-menu-custom-fields\wp-menu-custom-fields.php' ) ...\plugin.php:2255
4 0.8461 18996672 wp_menu_custom_fields_plugin_loader( ) ...\wp-menu-custom-fields.php:32

**Comment by vilm725** [comment]
Hi 👋🏼 Thanks for posting my email. Unfortunately, I don't have resolved this bug 😢

**Comment by SID177** [comment]
WordPress function [validate_files](https://developer.wordpress.org/reference/functions/validate_file/) returns 2 for Windows drive path, which wasn't checked before in autoloader.
We've addressed this in `v1.0.1` of this plugin.
