### ISSUE TITLE
Video added via shortcode not visible properly - twenty-twentyone theme 

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/wp-menu-custom-fields#50]
Vide added in custom menu field is not visible properly in twentytwentyone theme. 

Steps to reproduce: 
1. Install and activate the WP menu custom fields and navigate to Appearance -> Menu. 
2. Add the shortcode for the menu and observe the issue on the menu. 

https://user-images.githubusercontent.com/44057535/168542317-36b2e7bd-11c2-405d-af30-6d34ca2a66af.mp4

**Comment by SonaliThakkar25** [comment]
This is the old bug but need to check this also

**Comment by SonaliThakkar25** [comment]
Why this is marked as "Not Applicable" we just need to make sure rendered element have proper margin, padding, and spacing.
@Pradeep1308

**Comment by Pradeep1308** [comment]
@SonaliThakkar25 I've not marked this as not applicable, added same as issue 59

**Comment by alvitazwar** [comment]
This issue is resolved in develop branch as its a duplicate issue hense closing this one
