### ISSUE TITLE
Test plugin with WordPress and PHP latest versions.

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/wp-menu-custom-fields#51]
@alvitazwar Perform thorough testing of [WP Menu Custom Fields v1.0.2 ](https://wordpress.org/plugins/wp-menu-custom-fields/)plugin with WordPress 6.0.2 and PHP 8.1 version and report issues for same.  

Refer these test cases: https://docs.google.com/spreadsheets/d/1SUyVZsr0hsj9Wpt3pnYpPjgb68fMMj2sgA5MjTTGOw0/edit#gid=846109294

Create new test cases if required and add to same test cases.

Make sure you cover following points:
- Test plugin on single and MU site
- Test plugin with cross browser to check if everything works fine
- Quick test in responsive mode
- Add multiple menu items and check the behavior of plugin
- Look out for console errors and notices/warnings in error log

Share updates in comments..

cc: @SonaliThakkar25

**Comment by SonaliThakkar25** [comment]
Also Check if the basic UI is there or not, means if some other user installing the plugin then things should look good when rendered because plugin usually inherit the default styles.

**Comment by alvitazwar** [comment]
@SonaliThakkar25  Okay I will check that.

**Comment by alvitazwar** [comment]
This testing is also completed in develop branch

**Comment by alvitazwar** [comment]
Update: Only for adding audio shortcode, In local, using PHP 8.0, getting  Fatal error. 
<img width="1438" alt="Screenshot at Oct 17 16-25-08" src="https://user-images.githubusercontent.com/55917380/196154417-1e645a34-ced2-48f9-ba80-0af0d80abde0.png">

CC: @shreyasikhar  @SonaliThakkar25

**Comment by shreyasikhar** [comment]
@alvitazwar This is ready for review.
To test, switch to PHP version 8.x.x and clone the branch `feature/GH-51`

cc: @SonaliThakkar25

**Comment by alvitazwar** [comment]
@shreyasikhar  I am seeing that, `feature/GH-51` fixed the fatal error problem, but the design seems to be not fixed.  can you please sync the design fixes from  `feature/GH-82` and sync it to develop? Rest looks fine to me
<img width="1385" alt="Screenshot at Oct 17 17-26-31" src="https://user-images.githubusercontent.com/55917380/196165677-ce4b810f-58d5-4698-8e5e-78d7b7f6151b.png">

**Comment by shreyasikhar** [comment]
The `feature/GH-51` and `feature/GH-82` PRs are still waiting on approval, will update once it is merged.

**Comment by alvitazwar** [comment]
Thanks for the update

**Comment by shreyasikhar** [comment]
@alvitazwar PHP fatal error issue is fixed on develop, let me know if all looks good to merge it in master.
Thanks.

**Comment by alvitazwar** [comment]
I cross-checked develop branch with the fixes and It seems to be fixed and ready to push on master

**Comment by shreyasikhar** [comment]
@alvitazwar PHP fatal error issue is fixed on master as well.

cc: @SonaliThakkar25

**Comment by alvitazwar** [comment]
This issue is fixed and working fine on master, Hence closing this issue.
