### ISSUE TITLE
UI: Broken in both twenty twenty one and twenty twenty theme

### ISSUE THREAD

**Issue by alvitazwar** [rtCamp/wp-menu-custom-fields#52]
When Any video, audio, or link is added to the menu then in both the themes Design seems to be broken in All the menus.
visit: https://alvi-tazwar.rt.gw/

- [ ]  twenty twenty : desktop
https://prnt.sc/Uh76lGq6j_VY

- [ ] twenty twenty : mobile
https://prnt.sc/7dNOYavw8Kd2

- [ ] twenty twenty : tab
https://prnt.sc/DHqUnMqrLgAe

- [ ]  twenty-twenty-one : desktop
https://prnt.sc/RUtKpHJDNhxB

- [ ] twenty-twenty-one : mobile
https://prnt.sc/Js9Q3PC5xBPO

- [ ] twenty-twenty-one : tab
https://prnt.sc/ifpG9YUdjzFU

**Comment by SonaliThakkar25** [comment]
@Pradeep1308 why you have marked this as "Not Applicable" as I think this is the UI fixes

**Comment by Pradeep1308** [comment]
@SonaliThakkar25 this is added in the menu directly and it should be added in submenu that's why

**Comment by SonaliThakkar25** [comment]
@alvitazwar FYI

**Comment by alvitazwar** [comment]
@SonaliThakkar25  Noted
