### ISSUE TITLE
UI : Some Menu Display options  are missing in twenty-twenty-one theme

### ISSUE THREAD

**Issue by alvitazwar** [rtCamp/wp-menu-custom-fields#53]
Menu display options are missing in the twenty-twenty-one theme

Options appearing in the twenty-twenty-one theme 
https://prnt.sc/Tw-Yh_WsAArH

Options appearing in the twenty-twenty theme
https://prnt.sc/r9hLJjOWlmqX

**Comment by SonaliThakkar25** [comment]
@Pradeep1308 I think options are dependent upon the theme right?

**Comment by Pradeep1308** [comment]
@SonaliThakkar25 Yes these options are theme dependent.
