### ISSUE TITLE
Image Link field is not working. Changes are not reflected in front end.

### ISSUE THREAD

**Issue by alvitazwar** [rtCamp/wp-menu-custom-fields#55]
Image Link options are not working in all the cases of the plugin. It's not visible in both the themes and all the menu options. This video will cover all the sections 

Video
https://watch.screencastify.com/v/CuNMrqvLj6qy32sgUAuJ

**Comment by SonaliThakkar25** [comment]
@alvitazwar you can now test this

**Comment by alvitazwar** [comment]
@SonaliThakkar25  I tested this, And it works fine from the perspective of functionality. So we can go ahead to merge in master when All fixes will be done.

twenty-twenty: https://prnt.sc/wng21Efl_Vjb
twenty-twenty-one: https://prnt.sc/Invb67KqN0kN

**Comment by SonaliThakkar25** [comment]
@Pradeep1308 have we merged to the master's file?

**Comment by Pradeep1308** [comment]
@SonaliThakkar25 Once all issues are resolved then will merge all PR to master.

**Comment by alvitazwar** [comment]
@shreyasikhar  This issue is tested in develop and all other functionality is working as expected. You can merge it on master branch

**Comment by shreyasikhar** [comment]
@SonaliThakkar25 This issue is now fixed on master branch.

**Comment by alvitazwar** [comment]
I tested this issue in the master branch and it's working as expected. Hence Closing this issue.
 CC: @SonaliThakkar25
