### ISSUE TITLE
 Validate Image design in menu - WP version - 6.0.2

### ISSUE THREAD

**Issue by SonaliThakkar25** [rtCamp/wp-menu-custom-fields#56]
### Here are the steps to reproduce the issues:-

1. Select Image Radio button
2. Enter Custom Text
3. Upload image
4. Enter Image Caption
<img width="1512" alt="Screenshot 2022-09-14 at 12 50 36 PM" src="https://user-images.githubusercontent.com/55917380/190090366-5fc7585a-8a26-4137-a289-e6ea70180ba7.png">

**Need to fix broken image design when plugin activated**

**Comment by Pradeep1308** [comment]
@alvitazwar This needs to be tested only with the sub-menu as the plugin works with sub-menu items

**Comment by alvitazwar** [comment]
Okay i will update this with proper scenario

**Comment by SonaliThakkar25** [comment]
What is the update here?

**Comment by alvitazwar** [comment]
@SonaliThakkar25  This issue also got fixed during the other fixes. Hence changing the status

**Comment by shreyasikhar** [comment]
This is also fixed on master branch. 
cc: @alvitazwar @SonaliThakkar25

**Comment by alvitazwar** [comment]
This issue is fixed and working fine on master, Hence closing this issue.
