### ISSUE TITLE
Validate Video design in menu - WP version - 6.0.2 

### ISSUE THREAD

**Issue by SonaliThakkar25** [rtCamp/wp-menu-custom-fields#57]
### Here are the steps to regenerate the issue:-

1. Select Video Radio button
2. Enter Shortcode text
3. Add [video src= ""https://alvi-tazwar.rt.gw/wp-content/uploads/2022/09/https___handbook.rt_.gw_.mp4""]
4. Enter Caption text

**Comment by Pradeep1308** [comment]
@alvitazwar This needs to be tested only with the sub-menu as the plugin works with sub-menu items

**Comment by SonaliThakkar25** [comment]
Changed label as per the plugin functionality
