### ISSUE TITLE
UI: Multiple Sub menu Breaks the UI in the front end

### ISSUE THREAD

**Issue by alvitazwar** [rtCamp/wp-menu-custom-fields#58]
If the user puts Multiple submenus under one single Menu, then its breaks in the front end. The content of the menu should cover the whole section

Front-end:https://prnt.sc/g0sbli-dScpD
Back-end: https://prnt.sc/UBEkBjCC6n9n

**Comment by SonaliThakkar25** [comment]
@Pradeep1308 can we make sure multiple sub menu have at least proper spacing and CSS

**Comment by Pradeep1308** [comment]
@SonaliThakkar25 Actually this is working fine 2020 theme and the issue is coming in the 2021 theme, I'll try to implement the same thing on the 2021 theme.

**Comment by shreyasikhar** [comment]
@alvitazwar This is ready for review.
To test, please clone from branch `feature/GH-64` and let me know if any changes required.

cc: @SonaliThakkar25

**Comment by alvitazwar** [comment]
- [ ] Case one: 

If the user adds one menu and adds multiple submenus(max: 2 for current version target.) (except Video shortcode) the design then,
config: https://prnt.sc/24jKhfHPQxXR
front end output will look
twenty-twenty-one: https://prnt.sc/OnICkwylvYzj
twenty-twenty: https://prnt.sc/HUEnWXFX5YJ2
In both of the themes, the design looks good and consistent to me. 

- [ ] Case two: 

If the user adds one menu and adds one sub-menu and under that sub-menu add another sub-menu item (except video shortcode) then,
config: https://prnt.sc/2IGugmsCuGeB
Frontend output will look like this: 
twenty-twenty-one:https://prnt.sc/1RYnfhMWSVG1
twenty-twenty: https://prnt.sc/xhJboU7fL5zk
In both of the themes, the design needs some minor fixes and for twenty-twenty-one it needs some tweaking as well. but the rest looks good to me. 

I will be able to test this issue in full throttle after https://github.com/rtCamp/wp-menu-custom-fields/issues/59  this issue is fixed

CC: @SonaliThakkar25  @shreyasikhar

**Comment by shreyasikhar** [comment]
I have merged the changes on develop branch, will create a separate branch for the above feedback.
cc: @SonaliThakkar25 @alvitazwar

**Comment by shreyasikhar** [comment]
@alvitazwar  This is ready for review.
To test, please clone from `feature/GH-58` and let me know if any feedback.

cc: @SonaliThakkar25

**Comment by alvitazwar** [comment]
<img width="1371" alt="Screenshot at Oct 10 14-05-40" src="https://user-images.githubusercontent.com/55917380/194823516-41fdc7dc-387d-4cb0-afc2-4fa1cb149781.png">
As I 've had only one piece of feedback but after the conversation, We came to the conclusion that 2nd layer submenu item has some padding issue with the twenty-twenty-one theme hence All the things are looking good to me.
CC: @SonaliThakkar25

**Comment by shreyasikhar** [comment]
This is also fixed on master branch. 
cc: @alvitazwar @SonaliThakkar25

**Comment by alvitazwar** [comment]
This issue is fixed and working fine on master, Hence closing this issue.
