### ISSUE TITLE
UI: If video is added as sub menu then UI design looks inconsistent.

### ISSUE THREAD

**Issue by alvitazwar** [rtCamp/wp-menu-custom-fields#59]
When the User Adds a video as the submenu item then in the front end the item appears with vast empty space.

Steps: 
Add a menu
Add a submenu 
Add video using shortcode in the submenu.
See the changes in the front-end

SS:https://prnt.sc/2oAwUFH9X-5V

**Comment by shreyasikhar** [comment]
@alvitazwar This is ready for review.
To test, please clone from branch `feature/GH-59` and let me know if any feedback.

cc: @SonaliThakkar25

**Comment by alvitazwar** [comment]
In the twenty-twenty-one:
<img width="1436" alt="video-2021" src="https://user-images.githubusercontent.com/55917380/194152158-f85ff397-d4e7-4e79-a3fc-afa0ea62b5d1.png">

 twenty-twenty: 
 
<img width="1439" alt="video 2020" src="https://user-images.githubusercontent.com/55917380/194152427-ec57bf47-9a73-4a91-958a-6dc51daa2e6c.png">

Both the cases' design looks fine to me. Please merge it with develop so that I can perform quick testing for all the issues

**Comment by shreyasikhar** [comment]
Thanks @alvitazwar for the review.
I think the issue #65 is similar to this, so we should have both the issues fixed in the branch `feature/GH-59`
@alvitazwar Can you please confirm this, thanks.

cc: @SonaliThakkar25

**Comment by shreyasikhar** [comment]
This is also fixed on master branch. 
cc: @alvitazwar @SonaliThakkar25

**Comment by alvitazwar** [comment]
This issue is fixed and working fine on master, Hence closing this issue.
