### ISSUE TITLE
UI: twenty twenty theme Design broke if Custom HTML added as submenu

### ISSUE THREAD

**Issue by alvitazwar** [rtCamp/wp-menu-custom-fields#60]
If the user adds custom HTML text as a submenu item of the menu the design looks broken.
SS: https://prnt.sc/xZ-Iel5-PSX6

**Comment by Pradeep1308** [comment]
Checked the issue, and it works as expected.
cc: @SonaliThakkar25

**Comment by SonaliThakkar25** [comment]
@Pradeep1308 please always mention the video or SS for the reference to avoid back n forth, also add the screen size, browser, etc important things so that testing can review and update the issue accordingly.
Let's make this practice.

**Comment by Pradeep1308** [comment]
All looks good, as seen in the ss below.

<img width="991" alt="Screenshot 2022-09-28 at 11 19 01 PM" src="https://user-images.githubusercontent.com/61630284/192853281-3aaca777-4379-480a-9747-d9152b9b5ad5.png">

cc: @SonaliThakkar25 @alvitazwar

**Comment by SonaliThakkar25** [comment]
@alvitazwar have you checked this again?

**Comment by alvitazwar** [comment]
<img width="1429" alt="Screenshot at Sep 30 22-50-37" src="https://user-images.githubusercontent.com/55917380/193319035-b9dba474-3721-429a-9c37-8f727e2c4728.png">

@Pradeep1308  Still I am getting this. In which branch you making the changes?

**Comment by shreyasikhar** [comment]
@alvitazwar I have fixed this issue with a PR here https://github.com/rtCamp/wp-menu-custom-fields/pull/69, let me know with the QA review if any changes required or not.
Thanks!

cc: @SonaliThakkar25

**Comment by alvitazwar** [comment]
@shreyasikhar  Great work. The changes are looking Good to me. After it merges with the dev and master I will quickly check all other functionalities are working with this change. 

CC: @SonaliThakkar25

**Comment by alvitazwar** [comment]
@shreyasikhar sure I will check and get back to you 👍👍

**Comment by alvitazwar** [comment]
@shreyasikhar  I Pulled the feature/GH-60 and the design looks good to me you can merge it with develop.

Ref: https://prnt.sc/hkCgIrkNkxG0

**Comment by shreyasikhar** [comment]
Just FYI, that the padding changes are merged into develop branch.

**Comment by SonaliThakkar25** [comment]
@alvitazwar has this been checked to the master branch?

**Comment by alvitazwar** [comment]
@SonaliThakkar25 Checking the master branch on local and develop branch. Will update you in sometime

**Comment by shreyasikhar** [comment]
@SonaliThakkar25 This is not merged in the master yet, I am planning to fix all bugs in develop first then Alvi will check every part of this plugin. If all changes looks fine from QA end, then we can move fixes to master branch.
cc: @alvitazwar

**Comment by SonaliThakkar25** [comment]
@shreyasikhar can we now move it to master branch

**Comment by shreyasikhar** [comment]
@SonaliThakkar25 Actually, testing is not done for full site on both themes in the develop. We are expecting this full site testing on develop after issues #59 and #65 gets merged into develop.
I am working on #59 and #65 today (will raise a PR today itself), we can then do full-site testing and move the changes to master if no feedback from QA.

Let me know if this is okay to you.

**Comment by shreyasikhar** [comment]
This is also fixed on master branch. 
cc: @alvitazwar @SonaliThakkar25

**Comment by alvitazwar** [comment]
This issue is fixed and working fine on master, Hence closing this issue.
