### ISSUE TITLE
UI: twenty-twenty theme UI design broke after adding multiple submenu item in one menu

### ISSUE THREAD

**Issue by alvitazwar** [rtCamp/wp-menu-custom-fields#61]
If user add a custom menu item and inside that add another custom menu item then design cropped in 100 percent screen resolution. 
Backend configuration: https://prnt.sc/9DgssC3o9HLl
Front end issue: https://prnt.sc/FzeZZTw01jkh

**Comment by SonaliThakkar25** [comment]
This can be considered as a feature, we can take this once the current plugin gets stable

**Comment by shreyasikhar** [comment]
This is also fixed on master branch. 
cc: @alvitazwar @SonaliThakkar25

**Comment by alvitazwar** [comment]
This issue is fixed and working fine on master, Hence closing this issue.
