### ISSUE TITLE
UI: twenty-twenty-one theme UI design shows inconsistencies after adding multiple submenu item in one menu

### ISSUE THREAD

**Issue by alvitazwar** [rtCamp/wp-menu-custom-fields#62]
If user add a custom menu item and inside that add another custom menu item then the no design changes are reflected in the theme

Backend configuration: https://prnt.sc/9DgssC3o9HLl
Front end : https://prnt.sc/v0U0Bq-t-XhM

**Comment by SonaliThakkar25** [comment]
This bug can be considered a feature.

**Comment by shreyasikhar** [comment]
This is also fixed on master branch. 
cc: @alvitazwar @SonaliThakkar25

**Comment by alvitazwar** [comment]
This issue is fixed and working fine on master, Hence closing this issue.
