### ISSUE TITLE
UI:  twenty-twenty-one theme Image link submenu option UI enhancement

### ISSUE THREAD

**Issue by alvitazwar** [rtCamp/wp-menu-custom-fields#64]
In the twenty-twenty theme, the design looks perfect when the user adds an image_link in the front end. We can follow and implement the same image and text alignment enhancement in the twenty-twenty-one theme.

backend configuration: https://prnt.sc/1b0ThEqCDbka
twenty-twenty design:  https://prnt.sc/wng21Efl_Vjb
twenty-twenty-one design: https://prnt.sc/Invb67KqN0kN

CC: @SonaliThakkar25

**Comment by shreyasikhar** [comment]
@alvitazwar This is ready for review.
To test, please clone from branch `feature/GH-64` and let me know if any changes required.

cc: @SonaliThakkar25

**Comment by alvitazwar** [comment]
@shreyasikhar  I pulled the `feature/GH-64` branch and tested the fixes in my local.

In the twenty-twenty theme : 
<img width="1301" alt="imageLink-2020" src="https://user-images.githubusercontent.com/55917380/193873425-2278ab45-c912-4ac7-9a3b-85d79ed1e77c.png">

in the twenty-twenty-one theme: 
<img width="1432" alt="Image-link-2021" src="https://user-images.githubusercontent.com/55917380/193873518-e03723e1-72ac-453b-b741-73e9d63a8501.png">

now The design looks more consistent and polished than before. Great Work @shreyasikhar.

**Comment by shreyasikhar** [comment]
This issue is fixed in the develop branch. Will update it on master once video shortcode related issue gets fixed (expecting a fix PR today itself).

**Comment by alvitazwar** [comment]
@SonaliThakkar25  This Issue is fixed in develop branch. So after fixing all other issues. We can merge it with master in sometime.

**Comment by SonaliThakkar25** [comment]
Why it is not merged with master branch

**Comment by shreyasikhar** [comment]
This is also fixed on master branch. 
cc: @alvitazwar @SonaliThakkar25

**Comment by alvitazwar** [comment]
This issue is fixed and working fine on master, Hence closing this issue.
