### ISSUE TITLE
UI: twenty-twenty-one theme video-shortcode submenu option UI enhancement

### ISSUE THREAD

**Issue by alvitazwar** [rtCamp/wp-menu-custom-fields#65]
In the twenty-twenty theme, the design looks perfect when the user adds a video shortcode in the front end. We can follow and implement the same video player and text alignment enhancement in the twenty-twenty-one theme.

backend configuration: https://prnt.sc/iEJxXfojN9JJ
twenty-twenty design: https://prnt.sc/FnJv-4nr2SrV
twenty-twenty-one design: https://prnt.sc/nfeAJbF_BoUH

**Comment by SonaliThakkar25** [comment]
what is  the update here @shreyasikhar

**Comment by shreyasikhar** [comment]
@SonaliThakkar25 This will also get fixed with #59 once I merge the PR which is waiting on approval.

**Comment by shreyasikhar** [comment]
This is also fixed on master branch. 
cc: @alvitazwar @SonaliThakkar25

**Comment by alvitazwar** [comment]
This issue is fixed and working fine on master, Hence closing this issue.
