### ISSUE TITLE
Final Round of Testing

### ISSUE THREAD

**Issue by SonaliThakkar25** [rtCamp/wp-menu-custom-fields#78]
@alvitazwar,
###  Let's perform the final round of testing by keeping in mind the following things:
1. The issues we faced
2. Responsive
3. Cross Browser
4. Cross Theme checks

**Comment by alvitazwar** [comment]
Update: 
I pulled the develop branch in my local and dev site and test different themes today, Here is my observations:

- **Astra**: In the Astra theme, all our functionalities are working as expected. Here is a loom [Link](https://www.loom.com/share/2b6fcd60e74b438aa5524db59d483372)
- **Hello Elementor**: In this theme, if we add multiple menu items(more than 3) and add one sub-menu item for each, then the last 2 submenu items like image, image link, video, video shortcode section got cropped in full screen. Here is the loom [Link](https://www.loom.com/share/af99ebfb738149009cc3bc74468e4b35)
- **Neve**: In this theme, all our functionalities are working as expected. Here is a loom [Link](https://www.loom.com/share/40e2569b748f421588191b98ac8cdb9a)
- **OceanWp**:  In this theme, if we add multiple menu items(more than 3) and add one sub-menu item for each, then the last 2 submenu items like image, image link, video, video shortcode section got cropped in full screen. Also, All submenu contents are appearing left aligned which is not looking good. Here is the loom [Link](https://www.loom.com/share/74bfad43f327404986685845acd22ae7)

CC: @SonaliThakkar25

**Comment by shreyasikhar** [comment]
@SonaliThakkar25 I checked the above feedbacks from @alvitazwar and found out that these bugs that are coming in above mentioned themes because of css styles written in their own themes and overwriting our plugin's css.

We cannot write css to fix UI on all the themes, ideally these should be done from the respective themes only.
If we tried to fix these bugs from the plugin, then this changes may affect on other themes badly.

**Comment by SonaliThakkar25** [comment]
@shreyasikhar Agree!!! @alvitazwar You can make your final thoughts here

**Comment by alvitazwar** [comment]
I also agree with @shreyasikhar. We can ignore the theme wise fix..as different themes will have different css. So lets keep it for now and move forward with release.

**Comment by alvitazwar** [comment]
Today's Update:
1. Perform testing on WordPress 6.0.3 with default themes
2. Cross-check readme file and description. 
3. Perform sanity testing with updated zip
